config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do
      post :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id

  belongs_to :topic

  def self.special_blogs
    all
  end

  def self.feature_blog
    limit(2)
  end

  def self.recent
    order("created_at DESC")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs or /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.recent.published.page(params[:page]).per(5)
    end
    @page_title = "My portfolio Blog"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new(topic_id: 1)
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Post was removed." }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post status updated!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      # friendlyID Gem
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_sidebar_topics
      @set_sidebar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

  def blog_status_color(blog)
    if blog.draft?
      "color: red;"
    end
  end
end

app/views/blogs/_admin_actions.html.erb
 <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog), method: :post, style: blog_status_color(blog) %> /
      <%= link_to 'Edit', edit_blog_path(blog) %> /
      <%= link_to 'Destroy Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

app/views/blogs/_blog.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Piblished <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <%= render partial: 'admin_actions', locals: { blog: blog } %>
  <p><%= markdown blog.body %></p>
</article>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :topic_id, class: "form-label"%>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                selected: blog.topic.id, include_blank: true
                              },
                              class: "form-select"
                              )
    %>
  </div>

  <div class="mb-3">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>
    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control", rows: 15 %>
  </div>



  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<article class="blog-post">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</article>

app/views/blogs/index.html.erb
<h3 class="pb-4 mb-4 fst-italic border-bottom">
  From the Firehose
</h3>
<nav class="blog-pagination" aria-label="Pagination">
  <span>
    <%= link_to 'New Blog', new_blog_path, class: "btn btn-outline-primary"  if logged_in?(:site_admin) %>
  </span>
  <span>
    <%= link_to 'Topics', topics_path, class: "btn btn-outline-secondary"  if logged_in?(:site_admin) %>
  </span>
</nav>
<%= paginate @blogs %>
<%= render @blogs %>
<%= paginate @blogs %>

app/views/blogs/new.html.erb
<article class="blog-post">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</article>

app/views/blogs/show.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= @blog.title %></h2>
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb mb-1">
      <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
      <li class="breadcrumb-item"><%= link_to @blog.topic.title, topic_path(@blog.topic) %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= link_to @blog.title, root_path %></li>
    </ol>
    <span>
      <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to 'trash', @blog, method: :delete, data: { confirm: "Are you sure?" } if logged_in?(:site_admin) %>
    </span>
  </nav>
  <p class="blog-post-meta">Piblished <%= distance_of_time_in_words(@blog.created_at, Time.now) %> ago</p>
  <p class="blog-post-meta">
    <% if logged_in?(:site_admin) %>
      <%= link_to @blog.status, toggle_status_blog_path(@blog), method: :post %> /
      <%= link_to 'Edit', edit_blog_path(@blog) %> /
      <%= link_to 'Destroy Post', @blog, method: :delete, data: { confirm: 'Are you sure?' } %> /
    <% end %>
    <%= link_to 'Back', blogs_path %>
  </p>
  <p><%= markdown @blog.body %></p>
</article>