config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do
      post :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render body: nil
  end

  def angular
    @portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live."}
      else
        format.html { render :new }
      end
    end
  end

  def edit
    3.times { @portfolio_item.technologies.build }
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live."}
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def destroy

    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: "Portfolio was removed."}
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://placehold.jp/#{height}x#{width}.png"
  end

  def portfolio_img(img, type)
    if img
      img
    elsif type == "thumb"
      image_generator(height: "350", width: "200")
    else
      image_generator(height: "600", width: "400")
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item) do |f| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :subtitle, class: "form-label" %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :main_image, class: "form-label" %>
        <%= f.file_field :main_image, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :thumb_image, class: "form-label" %>
        <%= f.file_field :thumb_image, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :body, class: "form-label" %>
        <%= f.text_area :body, class: "form-control", rows: 13 %>
      </div>
    </div>
    <div class="col-md-12">
      <h2>Technology Used</h2>
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies %>
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col sortable-card" data-id="<%= portfolio_item.id%>">
  <div class="card shadow-sm">
    <%= image_tag portfolio_img(portfolio_item.thumb_image.url, "thumb"), width: '100%', height: '200px' %>
    <div class="card-body">
      <title><%= portfolio_item.title %></title>
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>
        <%= portfolio_item.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", portfolio_show_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" %>
          </button>
          <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
        </div>
        <small class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="mb-3 nested-fields">
  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolio Angular items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>
<% @portfolio_items.each do |portfolio_item| %>
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
<%= link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to "Delete Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit a Portfolio Item</h1>
  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>
  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image.url, "main"), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <hr>
      <h3>Technologies used</h3>
      <% @portfolio_item.technologies.each do |t|%>
        <p><%= t.name %></p>
      <% end %>
      <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: "btn btn-warning" %>
      </div>
      <% end %>
    </div>
  </div>
</div>